### ISSUE TITLE
Small question about migrating to remote DRAM

### ISSUE THREAD

**Issue by KunlinY** [csl-ajou/AutoTiering#2]
Hi there, I really like your paper and other research of your lab. I also try to do memory tiering in the industry. However, we mainly focus in page movement between local DRAM and local DCPMM, which is a much simpler problem. So I am curious about the `migrate`  improvement of your work. 

As you point out in the paper, latency for remote DRAM and local DCPMM is 133:173, which does not have significant difference if we consider the overhead of 
1. promote from L-DCPMM to R-DRAM.
2. migrate from R-DRAM to L-DRAM (if L-DRAM is free in the future).

![image](https://user-images.githubusercontent.com/17247609/146112392-ca4b9940-d853-4c6a-b4f5-459a03a5a625.png)

My questions are:
1. For a process with large working sets, how much % pages will reside in L-DRAM vs. in R-DRAM? And how much improvement is contributed by `migrate`? 
2. If we disable `migrate` or `exchange` operation, only keep movements between L-DRAM and L-DCPMM, how would the performance differ?
3. If we disable `exchange` but allow `migrate` between local and remote, i.e. use the original `migrate_pages`, how would the performance differ?

Thanks in advance for your attention.

**Comment by jhk16** [comment]
Hi! I appreciate your interest in our research.

First of all, we have measured memory access latency with sequential read. In real-world situations, there are more overheads for accessing remote memory because the process can have random access patterns (maybe more than 300ns at L-DCPMM).

You can quickly check the memory access latency and bandwidth by using [Intel MLC](https://www.intel.com/content/www/us/en/developer/articles/tool/intelr-memory-latency-checker.html), or more simply, just check the results of other research such as [Technical Report](https://www.nvsl.io/data/bib/pdfs/2019arXiv-AEP.pdf) and [FAST'20](https://www.usenix.org/conference/fast20/presentation/yang).

These are answers to your questions, assumed enabling AutoNUMA: 

1. Linux kernel allocates pages to the own local node. Thus, there are possible cases for the page ratio of Local DRAM vs Remote DRAM.
  * If you execute a multi-thread application covering all cores, threads on the local node(node-0) migrate pages from the remote DRAM to the local DRAM, and threads on the remote node(node-1) will migrate pages from the local node(node-0) to remote node(node-1).
  * If you execute a single thread application, there is no chance that pages are located to remote DRAM without thread migration.
  * Performance improvement from page migration also has many possibilities according to workloads. Because though we migrate pages to local DRAM, that process cannot access more after migration, which means `migrate` will cause just overhead. Therefore, it is needed to find out the access pattern of various applications to migrate pages for visibly performance improvement.

2. If we don't allow the system to migrate pages from remote socket to local socket, we can't reduce remote DCPMM access, which causes significant memory access overhead. If we allocate pages only single socket, it is a different result according to the memory access pattern of the application(sparsely or compact).

3. It may be the same as the above answer.

If you have more questions, feel free to ask.

**Comment by KunlinY** [comment]
Thank you for your detailed reply:) It does resolve my doubts. I ignored the case when memory is shared between multi threads. I was stuck by the loss and gain to migrate between L-DCPMM and R-DRAM. It makes more sense given your examples.

Still, I would like to double check that, for a page shared between multiple threads/cores, will it be migrated to R-DRAM result from the lack of space in L-DRAM? Assuming the last cpu access is current node. In other words, is it possible to migrate from local page (last cpuid=0, node=0) to remote memory (node=1)? I think it is different from the case you mentioned: migrate remote page (last cpuid=0, node=1) to local memory (node=0).

**Comment by jhk16** [comment]
In typical cases, there is no possible page migration from L-DRAM node(node-0) to R-DRAM node(node-1) on the default Linux kernel. 

However, with our OPM scheme (page demotion to lower-tier memory), we treat R-DRAM as a target node for page demotion. If the least accessed pages are demoted to other lower-tier memory nodes, we find the best demotion node satisfying sub-optimal performance. 

To find the best demotion node, we traverse the upper-tier node first, so if another upper-tier node has sufficient space, we set the demotion path to that node. If not, we traverse the most closely lower-tier memory node such as local socket DCPMM.

R-DRAM(node-1) is preferred node among target nodes(node-1, node-2(DCPMM), node-3(DCPMM)) because node-1 is sub-optimal node from node-0. Thus we can say "page migration local DRAM node to remote DRAM node can be possible in AutoTiering".

**Comment by KunlinY** [comment]
Oh, I see. Thanks again for your patience. We plan to test the strategy in our environment. The idea of AutoTier is wonderful and we really look forward for your groups' further work:)
